#!/usr/bin/env bash

MAGENTO="$( cd "$( dirname $( dirname "${BASH_SOURCE[0]}" ) )" && pwd )"

if [ -f "${MAGENTO}/app/etc/env.php" ]; then
  echo "Moving env.php to Limitless"
  mv "${MAGENTO}/app/etc/env.php" "${MAGENTO}/limitless/env.local.php"
fi

if [ -d "${MAGENTO}/pub/media" ]; then
  echo "Moving media to Limitless"
  mv "${MAGENTO}/pub/media" "${MAGENTO}/limitless/media"
fi

# Remove all un-tracked files except the env.php file
echo "Cleaning up the working directory"
git clean -x -f -d --exclude="limitless" --exclude=".idea" ${MAGENTO}

# Reinstall magento core from composer
echo "Reinstalling Magento2"
(cd ${MAGENTO} && composer install)

# Core bug fix
echo "Hack the Core to fix a deployment issues"
sed -i'tmp' 's/\$hasCustomization = false;/\$hasCustomization = true;/' vendor/magento/module-deploy/Model/DeployStrategyProvider.php
sed -i'tmp' 's/foreach (\$this->getCustomizationDirectories(\$area, \$themePath, \$locale) as $directory)/if(false)/' vendor/magento/module-deploy/Model/DeployStrategyProvider.php

# Move the deployment files into place
echo "Copying config.local.php to app/etc"
cp "${MAGENTO}/limitless/config.local.php" "${MAGENTO}/app/etc/config.local.php"
echo "Copying config.php to app/etc"
cp "${MAGENTO}/limitless/config.php" "${MAGENTO}/app/etc/config.php"

# Compile all dependencies
echo "Performing a DI compile"
(cd ${MAGENTO} && php bin/magento setup:di:compile)

# Compile all static content
echo "Building static content"
(cd ${MAGENTO} && php bin/magento setup:static-content:deploy --jobs 32 en_GB en_US es_ES de_DE)

# Remove the deployment files
echo "Removing temporary env.php file generated by the build"
rm "${MAGENTO}/app/etc/env.php"
echo "Removing config.local.php file generated by the build"
rm "${MAGENTO}/app/etc/config.local.php"

# Restore the local env file
if [ -f "${MAGENTO}/limitless/env.local.php" ]; then
  echo "Restoring local env.php file"
  mv "${MAGENTO}/limitless/env.local.php" "${MAGENTO}/app/etc/env.php"
fi

if [ -d "${MAGENTO}/limitless/media" ]; then
  echo "Restoring media"
  rm -r "${MAGENTO}/pub/media"
  mv "${MAGENTO}/limitless/media" "${MAGENTO}/pub/media"
fi