version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: limitless/deployment/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: limitless/deployment/permissions.sh
      timeout: 300
      runas: root
    - location: limitless/deployment/setup_upgrade.sh
      timeout: 300
      runas: nginx
  ApplicationStart:
    - location: limitless/deployment/application_start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: limitless/deployment/application_stop.sh
      timeout: 300
      runas: root