<?php
//@codingStandardsIgnoreFile
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 * @var $state \Limitless\Elastic\Model\Layer\State
 */
if ($block->canShowBlock()) { ?>

    <?php
    $state = $block->getLayer()->getState();
    ?>

    <div class="block filter" id="layered-filter-block"
         data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
        <?php $filtered = count($state->getFilters()) ?>
        <div class="block-title filter-title" data-count="<?php /* @escapeNotVerified */
        echo $filtered; ?>">
            <strong data-role="title"><?php /* @escapeNotVerified */
                echo __('Shop By') ?></strong>
        </div>

        <div class="block-content filter-content">
            <?php echo $block->getChildHtml('state') ?>

            <?php if ($state->getFilters() || $state->hasPriceFilter()) { ?>
                <div class="block-actions filter-actions">
                    <a href="<?php /* @escapeNotVerified */
                    echo $block->getClearUrl() ?>"
                       class="action clear filter-clear"><span><?php /* @escapeNotVerified */
                            echo __('Clear All') ?></span></a>
                </div>
            <?php }; ?>
            <?php $wrapOptions = false; ?>
            <?php
            foreach ($block->getFilters() as $filter){ ?>
                <?php if ($filter->getItemsCount()){ ?>
                    <?php
                    if (!$wrapOptions){ ?>
                        <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?php /* @escapeNotVerified */
                        echo __('Shopping Options') ?></strong>
                        <div class="filter-options" id="narrow-by-list" data-role="content"
                         data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
                        <?php $wrapOptions = true;
                    } ?>
                    <div data-role="collapsible" class="filter-options-item">
                        <div data-role="title" class="filter-options-title"><?php /* @escapeNotVerified */
                            echo __($filter->getName()) ?></div>
                        <div data-role="content" class="filter-options-content"><?php /* @escapeNotVerified */
                            echo $block->getChildBlock('renderer')->render($filter); ?></div>
                    </div>
                <?php
                }?>

            <?php }; ?>
                    <?php if ($wrapOptions){ ?>
                        </div>
        <?php } else { ?>
            <script>
                require([
                    'jquery'
                ], function ($) {
                    $('#layered-filter-block').addClass('filter-no-options');
                });
            </script>
            <?php }; ?>
        </div>
    </div>
<?php } ?>
