<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <div class="thankyou-message">
        <p><?php /* @escapeNotVerified */ echo __(' Thank you for your purchase! ') ?></p>
    </div>
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?php echo __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
            <p><?php echo __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif;?>
            <p><?php /* @escapeNotVerified */ echo __('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
    <?php endif;?>

    <?php if ($block->getCanViewOrder() && $block->getCanPrintOrder()) :?>
        <?php /* @escapeNotVerified */ echo __('Click <a href="%1" onclick="this.target=\'_blank\'" class="print">here</a> to print a copy of your order confirmation', $block->getPrintUrl()) ?>
        <?php echo $block->getChildHtml() ?>
    <?php endif;?>

    <?php echo $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
        </div>
    </div>
<!--    This script invalidates the localStorage cache and clears the minicart - MAGETWO-52593   -->
    <script>
        require([
            'Magento_Customer/js/customer-data'
        ], function (customerData) {
            var sections = ['cart'];
            customerData.invalidate(sections);
            customerData.reload(sections, true);
        });
    </script>
</div>
