<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$staticBlock = $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('homepage_categories')->toHtml();
$categories = explode(',', $staticBlock);
$storeUrl = $this->getBaseUrl();
echo '<div class="homepage_wrapper">';
foreach ($categories as $categoryItem) {
    $categoryItemArray = explode(":", $categoryItem);
    $category = $objectManager->get('Magento\Catalog\Model\Category')->load($categoryItemArray[0]);
    echo '<a href="' .$storeUrl . $category->getUrlKey() . '.html">';
    echo '<div class="category-links">';
    echo '<img src="/media/catalog/category/' . $category->getImage() . '" alt="' . $category->getName() . '" />';
    echo '<div class="cat-title">' . $category->getName() . '</div>';
    echo '<span>from </span><span class="price-from">£' . $categoryItemArray[1] . '</span>';
    echo '<div class="view-all">VIEW ALL</div>';
    echo '</div>';
    echo '</a>';
}
echo '</div>';