<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var \Magento\Cookie\Block\Html\Notices $block */ ?>
<?php if ($this->helper('Magento\Cookie\Helper\Cookie')->isUserNotAllowSaveCookie()): ?>
    <div class="message global cookie" id="notice-cookie-block" style="display: none">
        <div class="content">
            <p>
                <?php /* @escapeNotVerified */ echo __('Our website uses cookies to give you the best experience of our site.') ?>
                <span><?php /* @escapeNotVerified */ echo __('By using this site, you agree to the use of cookies.') ?></span>
                <?php /* @escapeNotVerified */ echo __('<a href="%1">Read our policy</a>.', $block->getPrivacyPolicyLink()) ?></p>
            <div class="actions">
                <button id="btn-cookie-allow" class="action allow secondary">
                    <span><?php /* @escapeNotVerified */ echo __('I agree');?></span>
                </button>
            </div>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "#notice-cookie-block": {
                "cookieNotices": {
                    "cookieAllowButtonSelector": "#btn-cookie-allow",
                    "cookieName": "<?php /* @escapeNotVerified */ echo \Magento\Cookie\Helper\Cookie::IS_USER_ALLOWED_SAVE_COOKIE ?>",
                    "cookieValue": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Cookie\Helper\Cookie')->getAcceptedSaveCookiesWebsiteIds() ?>,
                    "cookieLifetime": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Cookie\Helper\Cookie')->getCookieRestrictionLifetime()?>,
                    "noCookiesUrl": "<?php /* @escapeNotVerified */ echo $block->getUrl('cookie/index/noCookies') ?>"
                }
            }
        }
    </script>
<?php endif; ?>