<?php
/** @var \Limitless\InvoiceVat\Block\View $block */
?>
<div class="customblock">

<?php $_invoice = $block->getData('invoice'); ?>
<?php $_order = $block->getData('order'); ?>
<?php if ($_invoice && $_order): ?>
    <?php $companyNumber =  $block->getVariableValue('COMPANY_NUMBER',$block->getData('order')->getStoreId());?>

    <?php if ($block->getData('order')->getTaxAmount() > 0): ?>
           <?php $vatCode =  $block->getVariableValue('VAT',$block->getData('order')->getStoreId());?>
    <?php else: ?>
        <?php $vatCode = $block->getVariableValue('UKVAT',$block->getData('order')->getStoreId()); ?>
    <?php endif; ?>

    <?= /* @escapeNotVerified */ __('Company Registration Number:') ?>
    <?= /* @escapeNotVerified */ __($companyNumber) ?>
    <br>
    <?= /* @escapeNotVerified */ __('VAT Number:') ?>
    <?= /* @escapeNotVerified */ __($vatCode) ?>
    <br>

<?php endif; ?>
    </div>
