<div class="payment-footer">
    <div class="payment-footer-wrapper">
        <div class="payment-icons">
            <span class="visa"></span>
            <span class="mastercard"></span>
            <span class="paypal"></span>
            <span class="amex"></span>
            <span class="bank-transfer"></span>
            <span class="worldpay"></span>
            <div class="security-text"><span class="aws-secure"></span><span class="secure-text"><?php echo __('Our 128-bit encryption keeps your personal data secure and secure.'); ?></span></div>
        </div>
        <div class="hr-flags">
            <a class="hr-de-flag"></a>
            <a class="hr-fr-flag"></a>
            <a class="hr-it-flag"></a>
            <a class="hr-nl-flag"></a>
            <a class="hr-at-flag"></a>
            <a class="hr-be-flag"></a>
        </div>
    </div>
</div>