<ul class="footer links">
    <li class="hdr">Mein Konto</li>
    <li class="footer-toggle">
        <ul>
            <li class="nav item"><a href="#">Hilfe</a></li>
            <li class="nav item"><a href="#">Anmelden</a></li>
            <li class="nav item"><a href="#">Affiliate Netzwerk</a></li>
            <li class="nav item"><a href="#">Zahlung &amp;amp; Liefrung</a></li>
        </ul>
    </li>
</ul>
<ul class="footer links about">
    <li class="hdr">Über Hudson Reed</li>
    <li class="footer-toggle">
        <ul>
            <li class="nav item"><a href="#">Normen &amp; Garantie</a></li>
            <li class="nav item"><a href="#">Über uns</a></li>
            <li class="nav item"><a href="#">AGBs</a></li>
            <li class="nav item"><a href="#">FAQs</a></li>
        </ul>
    </li>
    <li class="footer-toggle last">
        <ul>
            <li class="nav item"><a href="#">Impressum</a></li>
            <li class="nav item"><a href="#">Sicherheit</a></li>
            <li class="nav item"><a href="#">Watt-Reichner</a></li>
            <li class="nav item"><a href="#">Blog</a></li>
        </ul>
    </li>
</ul>

<script type="text/x-magento-init">
    {
        "*": {
            "js/custom": {}
        }
    }
</script>