<ul class="footer links">
    <li>Mein Konto</li>
    <li class="nav item"><a href="#">Hilfe</a></li>
    <li class="nav item"><a href="#">Anmelden</a></li>
    <li class="nav item"><a href="#">Affiliate Netzwerk</a></li>
    <li class="nav item"><a href="#">Zahlung &amp; Liefrung</a></li>
</ul>
<ul class="footer links">
    <li>Uber Hudson Reed</li>
    <li class="nav item"><a href="#">Normen &amp; Garantie</a></li>
    <li class="nav item"><a href="#">Uber uns</a></li>
    <li class="nav item"><a href="#">AGBs</a></li>
    <li class="nav item"><a href="#">FAQs</a></li>
</ul>
<ul class="footer links">
    <li>&nbsp;</li>
    <li class="nav item"><a href="#">Impressum</a></li>
    <li class="nav item"><a href="#">Sicherheit</a></li>
    <li class="nav item"><a href="#">Watt-Reichner</a></li>
    <li class="nav item"><a href="#">Blog</a></li>
</ul>