<ul class="footer links">
    <li class="hdr"><?php echo __('My Account'); ?></li>
    <li class="footer-toggle">
        <ul>
            <li class="nav item"><a href="#"><?php echo __('Help'); ?></a></li>
            <li class="nav item"><a href="#"><?php echo __('Log In'); ?></a></li>
            <li class="nav item"><a href="#"><?php echo __('Affiliate Network'); ?></a></li>
            <li class="nav item"><a href="#"><?php echo __('Payment & Delivery'); ?></a></li>
        </ul>
    </li>
</ul>
<ul class="footer links about">
    <li class="hdr"><?php echo __('Über Hudson Reed'); ?></li>
    <li class="footer-toggle">
        <ul>
            <li class="nav item"><a href="#"><?php echo __('Standards & Warranty'); ?></a></li>
            <li class="nav item"><a href="#"><?php echo __('About Us'); ?></a></li>
            <li class="nav item"><a href="#"><?php echo __('T&Cs'); ?></a></li>
            <li class="nav item"><a href="#"><?php echo __('FAQs'); ?></a></li>
        </ul>
    </li>
    <li class="footer-toggle last">
        <ul>
            <li class="nav item"><a href="#"><?php echo __('Impressum'); ?></a></li>
            <li class="nav item"><a href="#"><?php echo __('Safety'); ?></a></li>
            <li class="nav item"><a href="#"><?php echo __('BTU Calculator'); ?></a></li>
            <li class="nav item"><a href="#"><?php echo __('Blog'); ?></a></li>
        </ul>
    </li>
</ul>

<script type="text/x-magento-init">
    {
        "*": {
            "js/custom": {}
        }
    }
</script>