<div class="homepage-banner">
    <img src="<?php echo $this->getViewFileUrl('images/hr-homepage-banner.jpg'); ?>" alt="homepage-banner" />
</div>

<div class="featured-categories">
    <a href="#"><img src="<?php echo $this->getViewFileUrl('images/duschen.jpg'); ?>" /></a>
    <a href="#"><img src="<?php echo $this->getViewFileUrl('images/armaturen.jpg'); ?>" /></a>
    <a href="#"><img src="<?php echo $this->getViewFileUrl('images/heizkorper.jpg'); ?>" /></a>
    <a href="#"><img src="<?php echo $this->getViewFileUrl('images/angebot.jpg'); ?>" /></a>
</div>
