<div class="homepage-banner">
    <img src="<?php echo $this->getViewFileUrl('images/hr-furniture-banner.jpg'); ?>" alt="homepage-banner" />
</div>


<div class="featured-categories">
    <a href="#"><img src="<?php echo $this->getViewFileUrl('images/duschen.jpg'); ?>" /></a>
    <a href="#"><img src="<?php echo $this->getViewFileUrl('images/armaturen.jpg'); ?>" /></a>
    <a href="#"><img src="<?php echo $this->getViewFileUrl('images/heizkorper.jpg'); ?>" /></a>
    <a href="#"><img src="<?php echo $this->getViewFileUrl('images/angebot.jpg'); ?>" /></a>
</div>

<div class="hr-home-blurb">
    <h2>Hudson Reed</h2>
    <h3>Spezialisten für Badezimmer, Duschen und Heizungen</h3>
    <p>Hudson Reed ist ein internationales Unternehmen, das seit 2005 Sanitärartikel für Badezimmer in mehrere europäische Länder einschließlich Deutschland, Österreich, Spanien, Italien, Frankreich und der Niederlande, als auch nach Belgien und den USA verkauft.</p>
    <p>In den letzten zehn Jahren hat ist Hudson Reed so stark vergrößert, dass es nun den Rang unter den am schnellsten anwachsenden Onlineunternehmen für Fachgeschäfte der Badezimmerinstallation und Designer-Heizkörper eingenommen hat.</p>
    <p>Wir bieten eine große und vielfältige Auswahl von über 1500 Produkten, von Design Heizkörpern bis hin zu Badheizkörper, Waschbeckenarmaturen, Wannenarmaturen, Küchenarmaturen, modernen thermostatischen Duschsets, Badmöbel, freistehende Badewannen, Duschbadewannen, Badezimmerzubehör, Toiletten, Duschkabinen, Duschtüren, etc...</p>
    <p>Lassen Sie sich von unseren verschiedenen Stilen und Farbmöglichkeiten berauschen, stellen Sie Ihr persönliches Spar zusammen und beheizen Sie Ihre Räumlichkeiten mit unseren luxuriösen und eﬀektiven Heizkörpern.</p>
</div>