<div class="social-links">
    <p class="hdr"><?php echo __('Social'); ?></p>
    <a class="facebook" href="https://www.facebook.com/HudsonReedES" target="_blank"><span>Facebook</span></a>
    <a class="pinterest" href="https://uk.pinterest.com/hudsonreedes/" target="_blank"><span>Pinterest</span></a>
    <a class="google-plus" href="https://plus.google.com/118318236369036544972/posts" target="_blank"><span>Google +</span></a>
    <a class="twitter" href="https://twitter.com/#!/hudsonreedes" target="_blank"><span>Twitter</span></a>
</div>