<div class="social-links">
    <p class="hdr">Social</p>
    <a class="facebook" href="https://www.facebook.com/DEHudsonReed" target="_blank"><span>Facebook</span></a>
    <a class="pinterest" href="https://www.pinterest.com/hudsonreedde/" target="_blank"><span>Pinterest</span></a>
    <a class="you-tube" href="https://www.youtube.com/user/HudsonReedDE?gl=DE&hl=de" target="_blank"><span>Youtube</span></a>
    <a class="google-plus" href="https://plus.google.com/104767129619467489746" target="_blank"><span>Google +</span></a>
    <a class="twitter" href="https://twitter.com/HudsonReedDE" target="_blank"><span>Twitter</span></a>
</div>