<script async type="text/javascript" src="//widget.trustpilot.com/bootstrap/v5/tp.widget.bootstrap.min.js"></script>
<div class="trustpilot-footer-banner">
    <div class="tp-footer-wrapper">
        <div class="tp-footer-logo">
            <img src="<?php echo $this->getViewFileUrl('images/trust-pilot-logo.svg'); ?>" alt="Trustpilot Logo"/>
        </div>
        <div class="trustpilot-widget" data-locale="de-DE" data-template-id="5406e65db0d04a09e042d5fc" data-businessunit-id="4eb284a00000640005116ec0" data-style-height="45px" data-style-width="100%" data-theme="dark"></div>
    </div>
</div>