<?php
/** @var \Limitless\TrustpilotApi\Block\TrustpilotApi $block */
?>

<div id="trustpilot-product">
    <h2><?=__('Our Customer Reviews')?></h2>
    <a id="tp-business-info" href="#" target="_blank">
        <div class="tp-trust-score"></div>
        <div class="tp-stars">
            <div class="star-1"><span class="star"></span></div>
            <div class="star-2"><span class="star"></span></div>
            <div class="star-3"><span class="star"></span></div>
            <div class="star-4"><span class="star"></span></div>
            <div class="star-5"><span class="star"></span></div>
        </div>
        <div class="tp-based-on"><?=__('Based on')?><span id="tp-number-of-reviews"></span><?=__('Reviews')?></div>
        <div class="tp-more-reviews"><?=__('See some of the reviews here.')?></div>
        <div class="tp-logo"><img src="<?=$block->getViewFileUrl('Limitless_TrustpilotApi::images/trustpilot-logo-light.svg') ?>" /></div>
    </a>
    <div class="tp-reviews-container">
        <div class="tp-latest-reviews owl-carousel"></div>
    </div>
</div>