<?php
/** @var \Limitless\TrustpilotApi\Block\TrustpilotApi $block */
?>

<div id="trustpilot-catalog">
    <a id="tp-business-link" href="#" target="_blank">
    <div class="tp-logo"><img src="<?=$block->getViewFileUrl('Limitless_TrustpilotApi::images/trustpilot-logo-light.svg') ?>" /></div>
    <div class="tp-stars">
        <div class="star-1"><span class="star"></span></div>
        <div class="star-2"><span class="star"></span></div>
        <div class="star-3"><span class="star"></span></div>
        <div class="star-4"><span class="star"></span></div>
        <div class="star-5"><span class="star"></span></div>
    </div>
    <div class="tp-business-info">
        <span class="tp-trustscore">
            <span><?=__('Trustscore')?></span>
            <span id="trust-score-value"></span>
        </span>
        <span class="tp-reviews">
            <span id="tp-number-of-reviews"></span>
            <span><?=__('Reviews')?></span>
        </span>
        <span class="more-reviews"><?=__('See some of the reviews here.')?></span>
    </div>
    </a>
    <div class="tp-latest-reviews"></div>
    <div class="tp-pagination"></div>
</div>